// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxsmqhjueqffuonwbllp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c21xaGp1ZXFmZnVvbndibGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTI5NTYsImV4cCI6MjA2MjcyODk1Nn0.veEDUr--iF8x76JftX04BFPaxf9-QZEg0lkGZ1YYUH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});